import type { Metadata } from 'next'

import './globals.scss'
import  Main  from '@/components/Main/Main'

export const metadata: Metadata = {
  title: 'Infinita Productions',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Main>
          {children}
        </Main>
      </body>
    </html>
  )
}
